version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rocket_report
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8081:80"
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  backend:
    container_name: rocketreport-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/var/www/html
      # - ./backend:/var/www/symfony
    ports:
      - "8080:80"
    depends_on:
      - mysql
      - redis
    environment:
      DATABASE_URL: "mysql://root:root@mysql:3306/rocket_report?serverVersion=8.0.32&charset=utf8mb4"
      REDIS_URL: "redis://redis:6379"

volumes:
  db_data:
