import { createContext, useState } from 'react';
import type { ReactNode } from 'react';

// Real RocketReport translations
const translations = {
    fr: {
        loading: 'Chargement en cours...',
        language: 'Langue',
        theme: 'Thème',
        welcome: 'Connexion à RocketReport',
        preparing: 'Vérification de l\'espace de travail...',

        // Hero Section
        tagline: '🚀 Génération de PDF automatisée',
        hero_title: 'Vos données API, transformées en rapports de génie',
        hero_subtitle: 'Connectez vos sources de données, injectez-les dans des templates personnalisés, exécutez votre propre logique JS/Python, et générez des PDF à la volée.',
        get_started: 'Créer un document',
        request_demo: 'Voir la documentation',

        // Features Section
        why_choose: 'Les super-pouvoirs de RocketReport',
        feat1_title: '📡 Connexion Sources API',
        feat1_desc: 'Récupérez dynamiquement vos données depuis n\'importe quelle API REST pour nourrir vos documents sans effort manuel.',
        feat2_title: '🎨 Templates Flexibles',
        feat2_desc: 'Concevez des modèles de documents intelligents et réutilisables qui s\'adaptent automatiquement aux données entrantes.',
        feat3_title: '⚙️ Code Processors Intégrés',
        feat3_desc: 'Transformez, filtrez et préparez vos données avec des scripts personnalisés avant leur injection dans le PDF final.',
        feat4_title: '📄 Génération Rapide',
        feat4_desc: 'Générez et téléchargez vos rapports PDF en un clin d\'œil avec notre moteur de rendu haute performance.',

        // How It Works
        how_title: 'Comment ça marche ?',
        step1_title: '1. Connecter l\'API',
        step1_desc: 'Ajoutez votre source de données REST.',
        step2_title: '2. Créer les Templates',
        step2_desc: 'Créez vos modèles avec vos variables.',
        step3_title: '3. Processeur de Données',
        step3_desc: 'Manipulez la data avant injection.',
        step4_title: '4. Générer le PDF',
        step4_desc: 'Générez et téléchargez le rapport final.',

        // Auth Section
        login_title: 'Se connecter',
        register_title: 'S\'inscrire',
        email_label: 'Adresse E-mail',
        email_placeholder: 'vous@entreprise.com',
        password_label: 'Mot de passe',
        password_placeholder: '••••••••',
        name_label: 'Nom complet',
        name_placeholder: 'Jean Dupont',
        confirm_password_label: 'Confirmer le mot de passe',
        forgot_password: 'Mot de passe oublié ?',
        login_submit: 'Connexion',
        register_submit: 'Créer un compte',
        no_account: 'Pas encore de compte ?',
        have_account: 'Déjà un compte ?',
        sign_up_link: 'S\'inscrire',
        sign_in_link: 'Se connecter',

        // Navigation
        nav_dashboard: 'Dashboard',
        nav_templates: 'Templates',
        nav_api_sources: 'API Sources',
        nav_build: 'Build',
        nav_generations: 'Générations',
        nav_mcp: 'AI Server (MCP)',
        nav_npm: 'Paquet NPM',
        nav_docs: 'Documentation',

        // MCP Docs Page
        mcp_title: 'Connectez votre IA à RocketReport',
        mcp_subtitle: 'Utilisez le Model Context Protocol (MCP) pour permettre à Claude, ChatGPT ou Gemini de générer vos rapports.',
        mcp_install_title: 'Installation Rapide',
        mcp_install_step1: '1. Récupérez votre clé API dans les paramètres.',
        mcp_install_step2: '2. Ajoutez la configuration à votre client IA.',
        mcp_conf_title: 'Configuration Claude Desktop',
        mcp_conf_desc: 'Ajoutez ce bloc à votre fichier `claude_desktop_config.json` :',
        mcp_features_title: 'Ce que l\'IA peut faire',
        mcp_feat_data: 'Analyser vos sources de données en temps réel.',
        mcp_feat_build: 'Écrire du code de transformation (JS/Python).',
        mcp_feat_gen: 'Générer et vous envoyer le PDF final.',

        // Common actions
        btn_refresh: 'Rafraîchir',
        btn_cancel: 'Annuler',
        btn_save: 'Sauvegarder',
        btn_create: 'Créer',
        btn_update: 'Mettre à jour',
        btn_delete: 'Supprimer',
        btn_edit: 'Modifier',
        btn_back: 'Retour',
        btn_new: 'Nouveau',
        btn_add: 'Ajouter',
        btn_preview: 'Aperçu',
        btn_saving: 'Sauvegarde…',
        btn_next: 'Suivant',
        btn_prev: 'Précédent',
        err_delete: 'Erreur lors de la suppression.',
        err_network: 'Erreur réseau ou serveur',
        err_download: 'Erreur lors du téléchargement.',

        // Dashboard
        dash_subtitle: 'Voici un aperçu de votre espace de travail.',
        dash_stat_generations: 'Générations',
        dash_example_templates: 'Templates exemples',
        dash_example_hint: 'Prévisualisez le rendu de chaque format, puis créez-les en un clic',
        dash_created: 'Créé',

        // API Sources page
        api_subtitle: 'Connecteurs vers vos APIs externes',
        api_new: 'Nouvelle source',
        api_empty_title: 'Aucune source API',
        api_empty_desc: 'Connectez votre première API REST pour alimenter vos rapports en données.',
        api_add: 'Ajouter une source',
        api_test_idle: 'Tester la connexion',
        api_test_loading: 'Test en cours…',
        api_test_ok: 'Connexion OK',
        api_test_error: 'Connexion échouée',
        api_auth_none: 'Aucune auth',
        api_delete_confirm: 'Supprimer cette source API ?',
        api_err_load: 'Impossible de charger les sources API.',

        // API Source modal
        api_modal_new: 'Nouvelle source API',
        api_modal_edit: 'Modifier la source API',
        api_field_name: 'Nom *',
        api_field_name_ph: 'Ex: API Météo, CRM interne…',
        api_field_desc: 'Description',
        api_field_desc_ph: 'Description optionnelle…',
        api_field_url: 'URL de base *',
        api_field_url_ph: 'https://api.example.com/v1',
        api_auth_section: 'Authentification',
        api_auth_bearer_label: 'Token Bearer',
        api_auth_key_label: 'Clé API',
        api_auth_basic_label: 'Identifiants (login:motdepasse)',
        api_headers_section: 'En-têtes personnalisés',
        api_header_key: 'Clé',
        api_header_value: 'Valeur',
        api_header_add: 'Ajouter un en-tête',
        api_err_name: 'Le nom est requis.',
        api_err_url: "L'URL de base est requise.",
        api_err_url_invalid: "L'URL n'est pas valide.",
        api_err_save: 'Erreur lors de la sauvegarde.',
        api_create_btn: 'Créer la source',

        // Templates page
        tpl_subtitle: 'Modèles de documents intelligents et réutilisables',
        tpl_new_title: 'Créer un template',
        tpl_new_desc: 'Partez de zéro ou utilisez l\'éditeur visuel',
        tpl_upload_title: 'Importer un fichier',
        tpl_upload_desc: 'Word, HTML, Markdown — on s\'adapte',
        tpl_empty_title: 'Aucun template',
        tpl_empty_desc: 'Créez votre premier template pour commencer à générer des rapports.',
        tpl_err_load: 'Impossible de charger les templates.',
        tpl_err_upload: 'Erreur lors de l\'analyse du fichier.',
        tpl_delete_confirm: 'Supprimer ce template ?',
        tpl_drop_hint: 'Glissez un fichier ou cliquez pour en sélectionner un',
        tpl_drop_formats: 'Formats supportés : .html, .docx, .md',
        tpl_uploading: 'Analyse en cours…',
        tpl_upload_success: 'Fichier analysé — ouvrir dans l\'éditeur',
        tpl_upload_btn: 'Importer',

        // Generations page
        gen_subtitle: 'Lancez et téléchargez vos rapports générés',
        gen_no_builds: 'Aucun build configuré',
        gen_no_builds_desc: 'Créez d\'abord un build dans la section "Build" pour lancer des générations.',
        gen_generate: 'Générer',
        gen_generating: 'Génération…',
        gen_download: 'Télécharger',
        gen_downloading: 'Téléchargement…',
        gen_history: 'Historique',
        gen_history_empty: 'Aucune génération pour ce build.',
        gen_cached: 'Rapport déjà en cache ✓',
        gen_success_msg: 'Rapport généré ✓',
        gen_err_gen: 'Erreur de génération',
        gen_col_date: 'Date',
        gen_col_format: 'Format',
        gen_col_status: 'Statut',
        gen_col_action: 'Action',
        gen_status_success: 'Succès',
        gen_status_failed: 'Échec',
        gen_status_pending: 'En attente',
        gen_err_load: 'Impossible de charger les builds.',

        // Build page
        build_subtitle: 'Configurez vos pipelines : source API → transformation → template',
        build_new: 'Nouveau build',
        build_empty_title: 'Aucun build',
        build_empty_desc: 'Créez votre premier build pour connecter une source API à un template.',
        build_create_first: 'Créer un build',
        build_err_load: 'Impossible de charger les builds.',
        build_err_delete: 'Erreur lors de la suppression.',
        build_delete_confirm: 'Supprimer ce build ?',
        build_step1: 'Source API',
        build_step2: 'Code',
        build_step3: 'Template',
        build_step4: 'Finaliser',
        build_wizard_new: 'Nouveau build',
        build_wizard_edit: 'Modifier le build',
        build_src_label: 'Choisissez une source API',
        build_src_endpoint: 'Endpoint',
        build_src_method: 'Méthode',
        build_src_preview: 'Prévisualiser les données',
        build_src_loading: 'Chargement…',
        build_code_label: 'Code de transformation',
        build_code_hint: 'Transformez `apiData` → retournez les données à injecter dans le template',
        build_code_run: 'Exécuter',
        build_code_running: 'Exécution…',
        build_code_result: 'Résultat',
        build_code_no_result: 'Cliquez sur "Exécuter" pour tester votre code avec les données de l\'API.',
        build_code_input: 'Données d\'entrée (apiData)',
        build_code_no_data: '// Aucune donnée — testez d\'abord la source à l\'étape 1',
        build_tpl_label: 'Associez un template',
        build_tpl_optional: 'optionnel',
        build_tpl_desc: 'Le template sera utilisé lors de la génération pour mettre en forme les données.',
        build_tpl_none: '⊘ Aucun template',
        build_finalize_title: 'Finalisez votre build',
        build_name_label: 'Nom du build *',
        build_name_ph: 'Ex: Rapport mensuel ventes…',
        build_desc_label: 'Description',
        build_desc_ph: 'Description optionnelle…',
        build_summary_source: 'Source',
        build_summary_code: 'Code',
        build_summary_template: 'Template',
        build_summary_none: 'Aucun',
        build_summary_lines: 'lignes',
        build_save: 'Créer le build',
        build_update: 'Mettre à jour',
        build_saving: 'Sauvegarde…',
        build_err_name: 'Le nom du build est requis.',
        build_err_source: 'Sélectionnez une source API.',
        build_err_endpoint: "L'endpoint est requis.",
        build_err_code: 'Le code de transformation est requis.',
        build_err_save: 'Erreur lors de la sauvegarde.',

        // Navbar
        nav_settings: 'Paramètres',
        nav_profile: 'Profil',
        nav_logout: 'Déconnexion',

        // TemplateEditor
        editor_back: 'Retour',
        editor_save: 'Sauvegarder',
        editor_update: 'Mettre à jour',
        editor_saving: 'Sauvegarde…',
        editor_name_ph: 'Nom du template…',
        editor_desc_ph: 'Description (optionnel)',
        editor_code_only: 'Code uniquement',
        editor_split: 'Split',
        editor_preview_only: 'Aperçu uniquement',
        editor_preview_live: 'Aperçu en temps réel',
        editor_vars_label: 'Variables détectées :',
        editor_var_ph: 'Valeur test…',
        editor_var_each_ph: 'JSON ou val1,val2',
        editor_write_ph: 'Écrivez votre template Handlebars ici…',
        editor_err_name: 'Le nom du template est requis.',
        editor_err_content: 'Le contenu est requis.',
        editor_err_save: 'Erreur lors de la sauvegarde.',

        // TemplateModal
        modal_new_tpl: 'Nouveau template',
        modal_edit_tpl: 'Modifier le template',
        modal_tab_write: 'Écrire',
        modal_tab_upload: 'Importer',
        modal_upload_hint: 'Importez un fichier existant (.txt, .html, .pdf, .xlsx).\nLe système extraira automatiquement les variables et le contenu.',
        modal_drop_hint: 'Glissez un fichier ici ou parcourir',
        modal_drop_sub: 'PDF, Excel (.xlsx), CSV, HTML, TXT',
        modal_analyzing: 'Analyse en cours…',
        modal_analyzed_ok: 'Fichier analysé avec succès',
        modal_vars_extracted: 'variable(s) extraite(s)',
        modal_apply_upload: 'Utiliser ce template',
        modal_tpl_name_label: 'Nom du template *',
        modal_tpl_name_ph: 'Ex: Rapport mensuel, Facture client…',
        modal_format_label: 'Format',
        modal_desc_label: 'Description',
        modal_desc_ph: 'Description optionnelle…',
        modal_helpers_ref: '📖 Référence Handlebars',
        modal_content_label: 'Contenu Handlebars *',
        modal_content_ph: '<!DOCTYPE html>…',
        modal_cancel: 'Annuler',
        modal_create_tpl: 'Créer le template',
        modal_update_tpl: 'Mettre à jour',
        modal_saving: 'Sauvegarde…',
        modal_err_name: 'Le nom du template est requis.',
        modal_err_content: 'Le contenu est requis.',
        modal_err_save: 'Erreur lors de la sauvegarde.',

        // Footer
        footer_text: '© 2026 RocketReport. Construit pour l\'automatisation.',
        footer_links: 'Documentation | API | Contact'
    },
    en: {
        loading: 'Loading...',
        language: 'Language',
        theme: 'Theme',
        welcome: 'Connecting to RocketReport',
        preparing: 'Verifying workspace...',

        // Hero Section
        tagline: '🚀 Automated PDF Generation',
        hero_title: 'Your API Data, Transformed into Genius Reports',
        hero_subtitle: 'Connect your data sources, inject them into custom templates, run your own JS/Python logic, and generate PDFs on the fly.',
        get_started: 'Create a Document',
        request_demo: 'View Documentation',

        // Features Section
        why_choose: 'RocketReport Superpowers',
        feat1_title: '📡 API Sources Connection',
        feat1_desc: 'Dynamically fetch your data from any REST API to feed your documents without any manual effort.',
        feat2_title: '🎨 Flexible Templates',
        feat2_desc: 'Design smart, reusable document templates that automatically adapt to incoming data.',
        feat3_title: '⚙️ Integrated Code Processors',
        feat3_desc: 'Transform, filter, and prepare your data with custom scripts before injecting it into the final PDF.',
        feat4_title: '📄 Lightning Fast Generation',
        feat4_desc: 'Generate and download your PDF reports in the blink of an eye with our high-performance rendering engine.',

        // How It Works
        how_title: 'How It Works?',
        step1_title: '1. Connect API',
        step1_desc: 'Add your REST data source.',
        step2_title: '2. Create Templates',
        step2_desc: 'Build templates with your variables.',
        step3_title: '3. Data Processor',
        step3_desc: 'Manipulate data before injection.',
        step4_title: '4. Generate PDF',
        step4_desc: 'Generate and download the final report.',

        // Auth Section
        login_title: 'Sign In',
        register_title: 'Sign Up',
        email_label: 'Email Address',
        email_placeholder: 'you@company.com',
        password_label: 'Password',
        password_placeholder: '••••••••',
        name_label: 'Full Name',
        name_placeholder: 'John Doe',
        confirm_password_label: 'Confirm Password',
        forgot_password: 'Forgot Password?',
        login_submit: 'Sign In',
        register_submit: 'Create Account',
        no_account: 'Don\'t have an account?',
        have_account: 'Already have an account?',
        sign_up_link: 'Sign Up',
        sign_in_link: 'Sign In',

        // Navigation
        nav_dashboard: 'Dashboard',
        nav_templates: 'Templates',
        nav_api_sources: 'API Sources',
        nav_build: 'Build',
        nav_generations: 'Generations',
        nav_mcp: 'AI Server (MCP)',
        nav_npm: 'NPM Package',
        nav_docs: 'Documentation',

        // MCP Docs Page
        mcp_title: 'Connect your AI to RocketReport',
        mcp_subtitle: 'Use the Model Context Protocol (MCP) to let Claude, ChatGPT or Gemini generate your reports.',
        mcp_install_title: 'Quick Install',
        mcp_install_step1: '1. Get your API Key from settings.',
        mcp_install_step2: '2. Add the configuration to your AI client.',
        mcp_conf_title: 'Claude Desktop Configuration',
        mcp_conf_desc: 'Add this block to your `claude_desktop_config.json` file:',
        mcp_features_title: 'What the AI can do',
        mcp_feat_data: 'Analyze your data sources in real-time.',
        mcp_feat_build: 'Write transformation code (JS/Python).',
        mcp_feat_gen: 'Generate and send you the final PDF.',

        // Common actions
        btn_refresh: 'Refresh',
        btn_cancel: 'Cancel',
        btn_save: 'Save',
        btn_create: 'Create',
        btn_update: 'Update',
        btn_delete: 'Delete',
        btn_edit: 'Edit',
        btn_back: 'Back',
        btn_new: 'New',
        btn_add: 'Add',
        btn_preview: 'Preview',
        btn_saving: 'Saving…',
        btn_next: 'Next',
        btn_prev: 'Previous',
        err_delete: 'Error deleting.',
        err_network: 'Network or server error',
        err_download: 'Error downloading.',

        // Dashboard
        dash_subtitle: 'Here is an overview of your workspace.',
        dash_stat_generations: 'Generations',
        dash_example_templates: 'Example Templates',
        dash_example_hint: 'Preview the render of each format, then create them in one click',
        dash_created: 'Created',

        // API Sources page
        api_subtitle: 'Connectors to your external APIs',
        api_new: 'New source',
        api_empty_title: 'No API source',
        api_empty_desc: 'Connect your first REST API to feed your reports with data.',
        api_add: 'Add a source',
        api_test_idle: 'Test connection',
        api_test_loading: 'Testing…',
        api_test_ok: 'Connection OK',
        api_test_error: 'Connection failed',
        api_auth_none: 'No auth',
        api_delete_confirm: 'Delete this API source?',
        api_err_load: 'Unable to load API sources.',

        // API Source modal
        api_modal_new: 'New API Source',
        api_modal_edit: 'Edit API Source',
        api_field_name: 'Name *',
        api_field_name_ph: 'E.g.: Weather API, Internal CRM…',
        api_field_desc: 'Description',
        api_field_desc_ph: 'Optional description…',
        api_field_url: 'Base URL *',
        api_field_url_ph: 'https://api.example.com/v1',
        api_auth_section: 'Authentication',
        api_auth_bearer_label: 'Bearer Token',
        api_auth_key_label: 'API Key',
        api_auth_basic_label: 'Credentials (login:password)',
        api_headers_section: 'Custom Headers',
        api_header_key: 'Key',
        api_header_value: 'Value',
        api_header_add: 'Add a header',
        api_err_name: 'Name is required.',
        api_err_url: 'Base URL is required.',
        api_err_url_invalid: 'URL is not valid.',
        api_err_save: 'Error saving.',
        api_create_btn: 'Create source',

        // Templates page
        tpl_subtitle: 'Smart, reusable document templates',
        tpl_new_title: 'Create a template',
        tpl_new_desc: 'Start from scratch or use the visual editor',
        tpl_upload_title: 'Import a file',
        tpl_upload_desc: 'Word, HTML, Markdown — we adapt',
        tpl_empty_title: 'No templates',
        tpl_empty_desc: 'Create your first template to start generating reports.',
        tpl_err_load: 'Unable to load templates.',
        tpl_err_upload: 'Error analyzing the file.',
        tpl_delete_confirm: 'Delete this template?',
        tpl_drop_hint: 'Drop a file or click to select one',
        tpl_drop_formats: 'Supported formats: .html, .docx, .md',
        tpl_uploading: 'Analyzing…',
        tpl_upload_success: 'File analyzed — open in editor',
        tpl_upload_btn: 'Import',

        // Generations page
        gen_subtitle: 'Launch and download your generated reports',
        gen_no_builds: 'No build configured',
        gen_no_builds_desc: 'Create a build first in the "Build" section to launch generations.',
        gen_generate: 'Generate',
        gen_generating: 'Generating…',
        gen_download: 'Download',
        gen_downloading: 'Downloading…',
        gen_history: 'History',
        gen_history_empty: 'No generation for this build.',
        gen_cached: 'Report already cached ✓',
        gen_success_msg: 'Report generated ✓',
        gen_err_gen: 'Generation error',
        gen_col_date: 'Date',
        gen_col_format: 'Format',
        gen_col_status: 'Status',
        gen_col_action: 'Action',
        gen_status_success: 'Success',
        gen_status_failed: 'Failed',
        gen_status_pending: 'Pending',
        gen_err_load: 'Unable to load builds.',

        // Build page
        build_subtitle: 'Configure your pipelines: API source → transformation → template',
        build_new: 'New build',
        build_empty_title: 'No builds',
        build_empty_desc: 'Create your first build to connect an API source to a template.',
        build_create_first: 'Create a build',
        build_err_load: 'Unable to load builds.',
        build_err_delete: 'Error deleting.',
        build_delete_confirm: 'Delete this build?',
        build_step1: 'API Source',
        build_step2: 'Code',
        build_step3: 'Template',
        build_step4: 'Finalize',
        build_wizard_new: 'New build',
        build_wizard_edit: 'Edit build',
        build_src_label: 'Choose an API source',
        build_src_endpoint: 'Endpoint',
        build_src_method: 'Method',
        build_src_preview: 'Preview data',
        build_src_loading: 'Loading…',
        build_code_label: 'Transformation code',
        build_code_hint: 'Transform `apiData` → return data to inject into the template',
        build_code_run: 'Run',
        build_code_running: 'Running…',
        build_code_result: 'Result',
        build_code_no_result: 'Click "Run" to test your code with the API data.',
        build_code_input: 'Input data (apiData)',
        build_code_no_data: '// No data — test the source first at step 1',
        build_tpl_label: 'Associate a template',
        build_tpl_optional: 'optional',
        build_tpl_desc: 'The template will be used during generation to format the data.',
        build_tpl_none: '⊘ No template',
        build_finalize_title: 'Finalize your build',
        build_name_label: 'Build name *',
        build_name_ph: 'E.g.: Monthly sales report…',
        build_desc_label: 'Description',
        build_desc_ph: 'Optional description…',
        build_summary_source: 'Source',
        build_summary_code: 'Code',
        build_summary_template: 'Template',
        build_summary_none: 'None',
        build_summary_lines: 'lines',
        build_save: 'Create build',
        build_update: 'Update',
        build_saving: 'Saving…',
        build_err_name: 'Build name is required.',
        build_err_source: 'Select an API source.',
        build_err_endpoint: 'Endpoint is required.',
        build_err_code: 'Transformation code is required.',
        build_err_save: 'Error saving.',

        // Navbar
        nav_settings: 'Settings',
        nav_profile: 'Profile',
        nav_logout: 'Logout',

        // TemplateEditor
        editor_back: 'Back',
        editor_save: 'Save',
        editor_update: 'Update',
        editor_saving: 'Saving…',
        editor_name_ph: 'Template name…',
        editor_desc_ph: 'Description (optional)',
        editor_code_only: 'Code only',
        editor_split: 'Split',
        editor_preview_only: 'Preview only',
        editor_preview_live: 'Live preview',
        editor_vars_label: 'Detected variables:',
        editor_var_ph: 'Test value…',
        editor_var_each_ph: 'JSON or val1,val2',
        editor_write_ph: 'Write your Handlebars template here…',
        editor_err_name: 'Template name is required.',
        editor_err_content: 'Content is required.',
        editor_err_save: 'Error saving.',

        // TemplateModal
        modal_new_tpl: 'New Template',
        modal_edit_tpl: 'Edit Template',
        modal_tab_write: 'Write',
        modal_tab_upload: 'Import',
        modal_upload_hint: 'Import an existing file (.txt, .html, .pdf, .xlsx).\nThe system will automatically extract variables and content.',
        modal_drop_hint: 'Drop a file here or browse',
        modal_drop_sub: 'PDF, Excel (.xlsx), CSV, HTML, TXT',
        modal_analyzing: 'Analyzing…',
        modal_analyzed_ok: 'File analyzed successfully',
        modal_vars_extracted: 'variable(s) extracted',
        modal_apply_upload: 'Use this template',
        modal_tpl_name_label: 'Template name *',
        modal_tpl_name_ph: 'E.g.: Monthly report, Invoice…',
        modal_format_label: 'Format',
        modal_desc_label: 'Description',
        modal_desc_ph: 'Optional description…',
        modal_helpers_ref: '📖 Handlebars reference',
        modal_content_label: 'Handlebars content *',
        modal_content_ph: '<!DOCTYPE html>…',
        modal_cancel: 'Cancel',
        modal_create_tpl: 'Create template',
        modal_update_tpl: 'Update',
        modal_saving: 'Saving…',
        modal_err_name: 'Template name is required.',
        modal_err_content: 'Content is required.',
        modal_err_save: 'Error saving.',

        // Footer
        footer_text: '© 2026 RocketReport. Built for automation.',
        footer_links: 'Documentation | API | Contact'
    }
};

export type Language = keyof typeof translations;

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: keyof typeof translations['en']) => string;
}

export const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

interface LanguageProviderProps {
    children: ReactNode;
}

export const LanguageProvider = ({ children }: LanguageProviderProps) => {
    const [language, setLanguageState] = useState<Language>(() => {
        const savedLang = localStorage.getItem('app-lang') as Language;
        if (savedLang && ['fr', 'en'].includes(savedLang)) return savedLang;
        return 'fr';
    });

    const setLanguage = (lang: Language) => {
        setLanguageState(lang);
        localStorage.setItem('app-lang', lang);
    };

    const t = (key: keyof typeof translations['en']) => {
        return translations[language][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};
